name: Compile SCSS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Sass
      run: npm install -g sass
    - name: Compile SCSS to CSS
      run: sass index.scss:index.css
    - name: Commit CSS
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.css
        git commit -m "Auto-compile SCSS to CSS" || echo "No changes to commit"
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 确保使用这个 token
      run: git push
